GOBNS-1384 updated libs/deps, version bump
ifit/xamarin-launchdarkly-android pull request #5
Opened 2022-08-25 15:01 UTC by michaelhope-ifit

bringing the LD package up to 3.1.6 and changing dependencies accordingly

2022-08-29 16:12 UTC, parkerjifit approved these changes
Looks good!

2022-08-29 21:04 UTC, jacobt-ifit requested changes
There are some relative paths in the `.csproj` that should be absolute. Otherwise all looks good!

2022-08-29 21:04 UTC, jacobt-ifit commented on LaunchDarklyAndroidBinding/LaunchDarklyAndroidBinding.csproj
> +  <Import Project="..\..\..\..\..\tmp\nuget\Xamarin.AndroidX.Migration.1.0.8\build\monoandroid90\Xamarin.AndroidX.Migration.props" Condition="Exists('..\..\..\..\..\tmp\nuget\Xamarin.AndroidX.Migrati
These relative paths should probably be absolute (see the `Import` element below).

2022-08-29 21:04 UTC, jacobt-ifit commented on LaunchDarklyAndroidBinding/LaunchDarklyAndroidBinding.csproj
> +  <Import Project="..\..\..\..\..\tmp\nuget\Xamarin.AndroidX.MultiDex.2.0.1.5\build\monoandroid90\Xamarin.AndroidX.MultiDex.targets" Condition="Exists('..\..\..\..\..\tmp\nuget\Xamarin.AndroidX.Multi
More relative paths here.

2022-08-30 12:46 UTC, michaelhope-ifit commented
oops, I guess times havent changed much.

2022-08-30 14:10 UTC, jacobt-ifit approved these changes
👍

2022-08-30 14:10 UTC, merged